{
 "title": "API Performance",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(api_requests_total{endpoint!=\"/metrics\"}[1m]))",
     "legendFormat": "all endpoints"
    }
   ]
  },
  {
   "title": "Error rate (5xx)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(api_requests_total{status_code=~\"5..\"}[5m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Latency P95",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(api_request_duration_seconds_bucket[5m])))",
     "legendFormat": "p95 latency"
    }
   ]
  }
 ]
}